SonarSource/sonar-scanner-maven

its/projects/maven/modules-source-versions/higher-version/pom.xml, its/projects/maven/modules-source-versions/higher-version/src/main/java/org/johnnei/sonarqube/bugs/MyClass.java, its/projects/maven/modules-source-versions/pom.xml, its/projects/maven/modules-source-versions/same-version/pom.xml, its/projects/maven/modules-source-versions/same-version/src/main/java/org/johnnei/sonarqube/bugs/MyClass.java, its/src/test/java/com/sonar/maven/it/suite/MavenTest.java, src/main/java/org/sonarsource/scanner/maven/bootstrap/JavaVersionResolver.java
=> MSONAR-162: Provide more accurate Java source/target versions per module

pom.xml
=> MSONAR-171 upgrade plexus-utils from 3.0.22 to 3.2.1

its/pom.xml, its/src/test/java/com/sonar/maven/it/suite/AbstractMavenTest.java, its/src/test/java/com/sonar/maven/it/suite/LinksTest.java, its/src/test/java/com/sonar/maven/it/suite/MavenTest.java
Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-maven/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:
=> Upgrade sonar-ws to v7.9.1

pom.xml
=> MSONAR-179 update sonar-scanner-api to latest version

.github/workflows/release.yml, pom.xml
=> fix release script job name

pom.xml
Need to change version of artifact to patch release
=> Prepare for patch release

.github/workflows/release.yml, relocation/pom.xml
- BUILD-1187 Add job to publish relocation pom
The produced relocation pom can be reviewed here: https://oss.sonatype.org/content/repositories/orgcodehausmojosonar-maven-plugin-1009/
It is not published yet.
=> Release relocation pom

pom.xml
Update parent pom to enable cycloneDX plugin
Add sbom to the build
=> BUILD-1447 Add sbom to the build

pom.xml
I've decided to update it, since the version used comes from 2019
=> MSONAR-209 Bump maven-invoker-plugin to the latest version 3.6.0

src/main/java/org/sonarsource/scanner/maven/bootstrap/MavenProjectConverter.java, src/main/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapper.java, src/test/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapperTest.java
=> SCANMAVEN-214 Disable sonar.scanAll when sonar.tests is specified

pom.xml
=> SCANMAVEN-210: Move to Java 11

its/src/test/java/com/sonar/maven/it/suite/MavenTest.java, pom.xml, src/main/java/org/sonarsource/scanner/maven/SonarQubeMojo.java, src/main/resources/META-INF/plexus/components.xml
Co-authored-by: Evgeny Mandrikov <evgeny.mandrikov@sonarsource.com>
=> SCANMAVEN-217 Fix broken integration with maven encrypted secret

.github/workflows/releasability.yaml
Remove releasability conditions to allow manual execution and remove its status from status checks.
=> Fix releaseability

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
[SCANMAVEN-229](https://sonarsource.atlassian.net/browse/SCANMAVEN-229)
To review:
Make sure the files are the same as these
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml
https://raw.githubusercontent.com/SonarSource/sonar-dotnet-enterprise/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md?token=GHSAT0AAAAAACM3Q6EYDU5DNCGFOFCNBMAYZYSOQXA
Make sure that PullRequestCreated.yml has the correct Jira project on the last line …
=> SCANMAVEN-229 Add Jira integration

its/pom.xml, its/projects/maven/bootstrap-small-project/pom.xml, its/projects/maven/bootstrap-small-project/src/main/java/org/example/Hello.java, its/src/test/java/com/sonar/maven/it/suite/BootstrapTest.java, pom.xml, property-dump-plugin/src/main/java/org/sonar/dump/PropertyDumpPlugin.java
[SCANMAVEN-237](https://sonarsource.atlassian.net/browse/SCANMAVEN-237)
[SCANMAVEN-237]: https://sonarsource.atlassian.net/browse/SCANMAVEN-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-237 Test sensor context config, system properties, and environment variables passed to the bootstrapped JRE

its/projects/maven/bootstrap-small-project/pom.xml, its/src/test/java/com/sonar/maven/it/suite/BootstrapTest.java
[SCANMAVEN-243](https://sonarsource.atlassian.net/browse/SCANMAVEN-243)
[SCANMAVEN-243]: https://sonarsource.atlassian.net/browse/SCANMAVEN-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-243 The SonarScanner for Maven does not try to contact the server when the project is skipped

pom.xml
[SCANMAVEN-240](https://sonarsource.atlassian.net/browse/SCANMAVEN-240)
Thank You!
[SCANMAVEN-240]: …
=> SCANMAVEN-240 Remove outdated URL from pom.xml

pom.xml
[SCANMAVEN-246](https://sonarsource.atlassian.net/browse/SCANMAVEN-246)
[SCANMAVEN-246]: https://sonarsource.atlassian.net/browse/SCANMAVEN-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-246 Bump to version 5.0

src/main/resources/static/documentation.md
[SCANMAVEN-248](https://sonarsource.atlassian.net/browse/SCANMAVEN-248)
Part of MMF-4133
Thank You!
[SCANMAVEN-248]: …
=> SCANMAVEN-248 Add static documentation of the scanner

.cirrus.star
[SCANMAVEN-249](https://sonarsource.atlassian.net/browse/SCANMAVEN-249)
[SCANMAVEN-249]: https://sonarsource.atlassian.net/browse/SCANMAVEN-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-249 Upgrade cirrus-modules to v3

.github/workflows/ToggleLockBranch.yml
[SCANMAVEN-252](https://sonarsource.atlassian.net/browse/SCANMAVEN-252)
To review - make sure that 
* there's only one file
* the file is the same as [ToggleLockBranch.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/ToggleLockBranch.yml)
* The slack channel on the last line is correct for this repo
[SCANMAVEN-252]: https://sonarsource.atlassian.net/browse/SCANMAVEN-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-252 Add ToggleLockBranch.yml

pom.xml
[SCANMAVEN-254](https://sonarsource.atlassian.net/browse/SCANMAVEN-254)
[SCANMAVEN-254]: https://sonarsource.atlassian.net/browse/SCANMAVEN-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-254 Update parent pom to version 81.0.0.2300

relocation/pom.xml
[SCANMAVEN-250](https://sonarsource.atlassian.net/browse/SCANMAVEN-250)
[SCANMAVEN-250]: https://sonarsource.atlassian.net/browse/SCANMAVEN-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-250 Fix broken links coming from the relocation-pom's parent

.cirrus.yml
[SCANMAVEN-261](https://sonarsource.atlassian.net/browse/SCANMAVEN-261)
[SCANMAVEN-261]: https://sonarsource.atlassian.net/browse/SCANMAVEN-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-261 Validate IT using the latest maven 4 release candidate 2

its/src/test/java/com/sonar/maven/it/suite/BootstrapTest.java, its/src/test/java/com/sonar/maven/it/suite/MavenTest.java, pom.xml, src/main/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapper.java, src/test/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapperTest.java
[SCANMAVEN-265](https://sonarsource.atlassian.net/browse/SCANMAVEN-265)
[SCANMAVEN-265]: https://sonarsource.atlassian.net/browse/SCANMAVEN-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-265 Upgrade sonar-scanner-java-library

its/src/test/java/com/sonar/maven/it/suite/BootstrapTest.java, src/main/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapper.java, src/test/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapperTest.java
[SCANMAVEN-256](https://sonarsource.atlassian.net/browse/SCANMAVEN-256)
[SCANMAVEN-256]: https://sonarsource.atlassian.net/browse/SCANMAVEN-256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-256 Remove server type logging

pom.xml
[SCANMAVEN-242](https://sonarsource.atlassian.net/browse/SCANMAVEN-242)
[SCANMAVEN-242]: https://sonarsource.atlassian.net/browse/SCANMAVEN-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-242 rename sonar.projectKey to org.sonarsource.scanner.maven:sonar-scanner-maven

its/src/test/java/com/sonar/maven/it/ProxyAuthenticator.java, its/src/test/java/com/sonar/maven/it/suite/ProxyTest.java
[SCANMAVEN-274](https://sonarsource.atlassian.net/browse/SCANMAVEN-274)
[SCANMAVEN-274]: https://sonarsource.atlassian.net/browse/SCANMAVEN-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-274 Fix quality flaws

README.md, cirrus/cirrus-qa.sh, develop.md
[SCANMAVEN-265](https://sonarsource.atlassian.net/browse/SCANMAVEN-265)
[SCANMAVEN-265]: https://sonarsource.atlassian.net/browse/SCANMAVEN-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-265 Document how to run integration tests locally

README.md
[SCANMAVEN-242](https://sonarsource.atlassian.net/browse/SCANMAVEN-242)
[SCANMAVEN-242]: https://sonarsource.atlassian.net/browse/SCANMAVEN-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-242 update readme quality gate badge, because project key has changed

its/src/test/java/com/sonar/maven/it/suite/AbstractMavenTest.java, its/src/test/java/com/sonar/maven/it/suite/BootstrapTest.java, its/src/test/java/com/sonar/maven/it/suite/JavaTest.java, its/src/test/java/com/sonar/maven/it/suite/LinksTest.java, its/src/test/java/com/sonar/maven/it/suite/MavenTest.java, its/src/test/java/com/sonar/maven/it/suite/ProxyTest.java, property-dump-plugin/pom.xml, property-dump-plugin/src/main/java/org/sonar/dump/PropertyDumpPlugin.java, property-dump-plugin/src/test/java/org/sonar/dump/PropertyDumpPluginTest.java
[SCANMAVEN-278](https://sonarsource.atlassian.net/browse/SCANMAVEN-278)
[SCANMAVEN-278]: https://sonarsource.atlassian.net/browse/SCANMAVEN-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-278 Fix quality flaws

cirrus/cirrus-qa.sh, sonar-maven-plugin/pom.xml, sonar-maven-plugin/src/main/java/org/sonarsource/scanner/maven/SonarQubeMojo.java, sonar-maven-plugin/src/main/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapper.java, sonar-maven-plugin/src/test/java/org/sonarsource/scanner/maven/SonarQubeMojoTest.java, sonar-maven-plugin/src/test/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapperTest.java
[SCANMAVEN-264](https://sonarsource.atlassian.net/browse/SCANMAVEN-264)
[SCANMAVEN-264]: https://sonarsource.atlassian.net/browse/SCANMAVEN-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-264 Add support for SonarQube Cloud regions

its/src/test/java/com/sonar/maven/it/suite/ProxyTest.java, its/src/test/resources/proxy-settings.xml
[SCANMAVEN-271](https://sonarsource.atlassian.net/browse/SCANMAVEN-271)
[SCANMAVEN-271]: https://sonarsource.atlassian.net/browse/SCANMAVEN-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-271 Fix readability issues in ProxyTest

sonar-maven-plugin/src/main/java/org/sonarsource/scanner/maven/bootstrap/MavenUtils.java, sonar-maven-plugin/src/main/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapper.java, sonar-maven-plugin/src/main/java/org/sonarsource/scanner/maven/bootstrap/SourceCollector.java, sonar-maven-plugin/src/test/java/org/sonarsource/scanner/maven/bootstrap/MavenUtilsTest.java, sonar-maven-plugin/src/test/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapperTest.java
[SCANMAVEN-279](https://sonarsource.atlassian.net/browse/SCANMAVEN-279)
[SCANMAVEN-279]: https://sonarsource.atlassian.net/browse/SCANMAVEN-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-279 Clean up old code

its/projects/maven/irrelevant-encrypted-property/pom.xml, its/projects/maven/irrelevant-encrypted-property/src/main/java/org/example/Hello.java, its/src/test/java/com/sonar/maven/it/suite/MavenTest.java, sonar-maven-plugin/src/main/java/org/sonarsource/scanner/maven/bootstrap/MavenUtils.java, sonar-maven-plugin/src/main/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapper.java, sonar-maven-plugin/src/main/java/org/sonarsource/scanner/maven/bootstrap/ScannerBootstrapperFactory.java, sonar-maven-plugin/src/test/java/org/sonarsource/scanner/maven/bootstrap/MavenUtilsTest.java
[SCANMAVEN-228](https://sonarsource.atlassian.net/browse/SCANMAVEN-228)
[SCANMAVEN-228]: https://sonarsource.atlassian.net/browse/SCANMAVEN-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-228 Ignore Irrelevant Encrypted Properties

sonar-maven-plugin/pom.xml
[SCANMAVEN-280](https://sonarsource.atlassian.net/browse/SCANMAVEN-280)
[SCANMAVEN-280]: https://sonarsource.atlassian.net/browse/SCANMAVEN-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-280 Log the SonarQube Cloud Region

.github/workflows/releasability.yaml, its/pom.xml, its/src/test/java/com/sonar/maven/it/suite/AbstractMavenTest.java, property-dump-plugin/pom.xml
[SCANMAVEN-284](https://sonarsource.atlassian.net/browse/SCANMAVEN-284)
Part of 
Thank You!
[SCANMAVEN-284]: …
=> SCANMAVEN-284 Bump releasability workflow version

README.md
[SCANMAVEN-297](https://sonarsource.atlassian.net/browse/SCANMAVEN-297)
Thank You!
[SCANMAVEN-297]: …
=> SCANMAVEN-297 Update README.md with copy from Product Marketing

.cirrus.yml
[SCANMAVEN-303](https://sonarsource.atlassian.net/browse/SCANMAVEN-303)
[SCANMAVEN-303]: https://sonarsource.atlassian.net/browse/SCANMAVEN-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-303 Delete mend_scan_task

shadow-scan-and-issue-replication.sh
[SCANMAVEN-295](https://sonarsource.atlassian.net/browse/SCANMAVEN-295)
[SCANMAVEN-295]: https://sonarsource.atlassian.net/browse/SCANMAVEN-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANMAVEN-295 Wait for the sonarcloud compute engine to finish
